# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 434b8be1463dde331ff292d100118ab02690ae8e153a79e22d2bf3abbda5d929481c675c4b9c948e94332b87792b18646e08de653eadd02077389ef1f975a627

test:
  secret_key_base: 34e1956a036584a72cf9e99f4f745045726a7ec3b8d42d7afe8b3ed17add7c3627c7d72a44629af79451128f7891184cbf488d7c1303c7df83b441ebaffcf914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
